title:            Data and Magnetics Research - C. Duncan
description:      Research into Magnetic Fields and Data Science - not neccessarily together
disqus_shortname: 
reading_time:     true
words_per_minute: 200

# When testing locally leave blank or use http://localhost:4000
url: https://gitmo234.github.io

# Owner/author information
owner:
  name:           Christopher Duncan
  avatar:         avatar2.png
  bio:            "PhD Student, Remote Sensing Scientist, Tesla Owner, Pilot, Space Geek, Slacker."
  email:          Chrisd234@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: Gitmo234        
  facebook:       
  github: Gitmo234         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: test.jpg

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
